pynamodb/PynamoDB

pynamodb/models.py

Fix bug with falsy values (other than None) #56

---

pynamodb/models.py

Exclude None range_key from Model._get_keys()

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py

Fixes https://github.com/jlafon/PynamoDB/issues/109

Specify dayfirst=False in parse() call

---

pynamodb/models.py
pynamodb/tests/test_model.py

Correctly handle expected valuation generation for set types.

---

docs/conditional.rst

Relates to https://github.com/jlafon/PynamoDB/pull/108

Document conditional operation failure check.

---

pynamodb/models.py
pynamodb/tests/test_model.py

copied query limit code from @joshowen's fork after a discussion with him over email.
i wrote the tests.

fix limits

---

docs/batch.rst
pynamodb/models.py
pynamodb/tests/test_model.py

See comment in code for thorough explanation

Raise on multiple uses of attrs in query or scan conditions

---

pynamodb/connection/base.py
pynamodb/constants.py
pynamodb/tests/test_base_connection.py

getting a little more retry logic in
want to do more around configurability, but will come later

Retry on InternalServerError exceptions with backoff

---

pynamodb/models.py
pynamodb/tests/test_model.py

allow raw map attrs

---

pynamodb/models.py
pynamodb/tests/data.py
pynamodb/tests/test_model.py

@danielhochman @yedpodtrzitko from - https://github.com/jlafon/PynamoDB/issues/191

deserialize map attributes correctly

---

pynamodb/attributes.py
pynamodb/tests/data.py
pynamodb/tests/test_model.py

Allow raw map attributes in subclassed map attributes

---

pynamodb/attributes.py
pynamodb/tests/data.py
pynamodb/tests/test_attributes.py
pynamodb/tests/test_model.py

Allow longs as members of maps + lists in python 2

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_model.py

Incorrect assumption of consumed capacity returned. Expected a value but was a dict.
@danielhochman

Pynamo rate_limited_scan fix for consumed capacity

---

pynamodb/models.py
pynamodb/tests/test_model.py

Consume all pages when counting

---

.gitignore
.travis.yml
requirements.txt
tox.ini

Switching to using pytest to run our unit tests.

Use pytest instead of nose

---

README.rst
docs/attributes.rst
docs/contributing.rst
docs/examples.rst
docs/index.rst
docs/release_notes.rst
pynamodb/tests/test_model.py

This also updates the badges on the README to be a little nicer

Update docs for the new repo location

---

pynamodb/attributes.py
pynamodb/tests/data.py
pynamodb/tests/test_attributes.py
pynamodb/tests/test_model.py

https://github.com/pynamodb/PynamoDB/issues/241 -- fix for
cc @garrettheel @lita

Fix for null deserialize

---

pynamodb/models.py
pynamodb/tests/test_model.py

https://github.com/pynamodb/PynamoDB/pull/163

Skip null check for batch delete

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py
requirements-dev.txt

Fixed PR #254 as asked by @garrettheel.

Ensure correct serialize is called for List and Map attributes

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py

https://github.com/pynamodb/PynamoDB/issues/212

catch value error and raise tabledoesnotexist

---

.travis.yml
pynamodb/attributes.py
pynamodb/models.py
pynamodb/tests/test_attributes.py
pynamodb/tests/test_model.py

Key attribute_values off the field name instead of attr_name.

---

pynamodb/attributes.py

To illustrate the issue and the proposed fix, consider the following Model definition:
```
>>> from pynamodb.attributes import Attribute, MapAttribute
>>> from pynamodb.models import Model
>>> class SubMapAttribute(MapAttribute): 
...     a = Attribute()
... 
>>> class SubModel(Model):
...     class Meta:
...         table_name='tbl'
...     sub_map = SubMapAttribute()
... 
>>> sm = SubModel(**{'sub_map': {'a': 'foo'}})
```
Because `sub_map` is an object instance, the following access of the `a` Attribute incorrectly returned the value bound to the `sub_map` instance:
```
>>> SubModel.sub_map
<__main__.SubMapAttribute object at 0x10c52b890>
>>> print(SubModel.sub_map.a)
None
>>> sm.sub_map.a
'foo'
```
That prevents code like `SubModel.sub_map.a.attr_name` from correctly returning the …

Fix attribute lookup from subclassed map attributes.

---

pynamodb/attributes.py
pynamodb/connection/base.py
pynamodb/expressions/condition.py
pynamodb/expressions/operand.py
pynamodb/expressions/projection.py
pynamodb/expressions/update.py
pynamodb/expressions/util.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_expressions.py
pynamodb/tests/test_table_connection.py

Both Condition and Update expressions have operands that can be:
- document paths
- attribute values
- functions specific to the expressions
This PR separates out "Operand" and its subclasses to allow them to be used in either Condition expressions or Update expression actions as appropriate.

Prepare for UpdateExpression API

---

pynamodb/models.py
pynamodb/tests/test_model.py

Re-implementation of @MarSoft's #167 on top of master.

Model.refresh() should reset all model attribuets. Fixes #166

---

pynamodb/models.py

Note:
* This makes use of BatchWrite() a documented part of the public API. Given that
PynamoDB does appear to use `_` for private API, I believe this is already
considered public.
* `auto_commit` doesn't appear to do what one might expect given the typical
meaning in traditional database APIs. This makes that explicit (changing the
name of the arg would of course be a breaking change). One may argue that
the lack of transactional or atomic batch puts in DynamoDB should lead the
user to assume semantics aren't what expected, but it still seems worth
calling out that a failing context may still emit writes to the database.

Improve documentation of batch writes.

---

docs/local.rst
docs/settings.rst

The existing link is just a 404.

Fix cross-reference to use a proper sphinx ref.

---

docs/tutorial.rst

Signed-off-by: jmphilli <jphillips@lyft.com>
@tagleader

doc update

---

docs/attributes.rst
pynamodb/attributes.py
pynamodb/tests/test_attributes.py

Update map attribute deserialization (fixes #358)

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py

Skip null attributes post serialization for maps

---

docs/attributes.rst

Fix method signatures in custom attribute docs

---

docs/tutorial.rst

Didn't realize this existed until later would have been nice to have known about it a little sooner.

Adding MapAttribute to tutorial

---

.coveragerc

Obviously the tests are not what we're trying to have high coverage of.

Omit tests from coverage measurement

---

README.rst

The same phrase is a few lines above

Delete duplicate phrase from README

---

docs/indexes.rst

Document last evaluated key

---

pynamodb/tests/mypy_helpers.py
requirements-dev.txt

Update mypy output parser for https://github.com/python/mypy/pull/6919

tests: bump to mypy 0.710

---

docs/release_notes.rst

release notes: key attribute types must match table

---

docs/rate_limited_operations.rst

Updating the docs to be explicit in stating that write rate limiting isn't supported.

Adding info on write rate limiting

---

docs/transaction.rst

Fix incorrect documentation for Transaction.update

---

README.rst

The instructions don't match the code example. I think there has been a little mismatch here.

Fix query instructions mistake in README

---

pynamodb/attributes.py

Fix simple typo: signifantly -> significantly

---

pynamodb/models.py

I had to do quite a bit of guess and check to figure these all out. It would be helpful if they were in the docs.
Thanks!

Add exception descriptions to the Docs

---

.travis.yml
docs/api.rst
docs/conf.py
docs/index.rst
docs/local.rst
docs/rate_limited_operations.rst
docs/release_notes.rst
docs/signals.rst
docs/transaction.rst
pynamodb/models.py
requirements-dev.txt

Also adding sphinx to CI to ensure docs validity going forward.

Fix docs syntax errors

---

pynamodb/attributes.py

Remove warning about collections.abc deprecation

---

pynamodb/connection/base.py
pynamodb/indexes.py
pynamodb/models.py
pynamodb/util.py
tests/test_model.py

Rename pythonic to camel_to_snake_case move util to top level

Rename pythonic to camel_to_snake_case move util to top level

---

examples/model.py

Add usage example for ListAttribute

---

pynamodb/models.py

Three year old typo.  Whoot!

---

pynamodb/models.py
tests/test_model.py

`DefaultMeta` is removed so that a model's Meta class is inherited from the parent class.
Note: this is technically a backwards-incompatible change for those users who relied on dynamically setting attributes of their Meta class without creating it first.

Support model class inheritance. Fixes #164

---

docs/release_notes.rst
pynamodb/connection/base.py
pynamodb/connection/table.py
pynamodb/models.py
pynamodb/pagination.py
pynamodb/settings.py
tests/test_base_connection.py

Most operations (except for table operations) have "operation settings" now.

Add operation settings to most operations

---

.github/workflows/test.yaml

This ensures that we run tests on PRs from forks

Fix github actions event targeting

---

pynamodb/indexes.py
tests/test_mypy.py

Index.scan: annotate return type

---

docs/release_notes.rst
pynamodb/attributes.py
tests/test_attributes.py

UTCDateTimeAttribute: support for pre-1000 dates

---

docs/examples.rst

Fix docs in examples.rst

---

docs/conditional.rst

Document https://github.com/pynamodb/PynamoDB/pull/653.

Document condition chaining

---

docs/rate_limited_operations.rst

Fixed typos in the code snippets.

Fixed typo in ratelimit documentation

---

docs/conditional.rst
docs/updates.rst
tests/integration/test_transaction_integration.py

Take [the preview](https://pynamodb--1141.org.readthedocs.build/en/1141/) for a spin.

Improve docs for conditional, update expressions

---

docs/release_notes.rst
pynamodb/__init__.py
pynamodb/exceptions.py
tests/test_exceptions.py

Backport of #1113 to 5.x branch.
Fixes #1155.

Fix exception message

---

pynamodb/signals.py
requirements-dev.txt

Fix mypy check by pinning blinker version

---

pynamodb/models.py
tests/test_model.py

Model.batch_get: add guard-rails

---

docs/index.rst
docs/release_notes.rst
docs/upgrading.rst
docs/upgrading_binary.rst
docs/upgrading_unicodeset.rst
pynamodb/exceptions.py

Add upgrade guide to docs

---

pynamodb/attributes.py

default must be immutable
https://pynamodb.readthedocs.io/en/latest/api.html\#pynamodb.attributes.Attribute

Fix documentation for MapAttribute
