pynamodb/PynamoDB

pynamodb/models.py

Without my fix, just a few lines below this line raises error:
`attribute_class = non_key_attribute_classes.get(attr_name, None)`
Unless **non_key_attribute_classes** is a dictionary.

If non_key_attribute_classes is None, .get() raises error

---

pynamodb/connection/base.py
pynamodb/models.py

Previously, if used a .get(hash_key, range_key) where bool(range_key)
was False, the range_key wouldn't actually show up in the query to
DynamoDB because the get_identifier_map function would simply use
the truthy evaluation `if range_key`. By changing this to an
explicit `if range_key is not None`, this allows gets when a Python
value would otherwise evaluate to False, e.g., 0.

range_key in get fails with truthy Falses

---

pynamodb/connection/base.py

I'm opening this pull request primarily to start a discussion.
This is a hack I did to circumvent boto's poor performance when parsing request bodies. It's unfortunate because it requires accessing underscore "protected" members of boto. It does improve performance significantly.
There is also behavior around error handling and exceptions from boto that need to be replicated. Maybe checking the status code and throwing on non-200s would be enough. I haven't explored PynamoDB's behavior in error scenarios yet.
TODO:

use boto to prepare request only

---

README.rst
pynamodb/connection/base.py
pynamodb/connection/table.py
pynamodb/constants.py
pynamodb/models.py
pynamodb/tests/test_base_connection.py
requirements.txt

Botocore v1.1.2 supports new parameters for adding a stream to a dynamo
table on creation. It's relatively straightforward to add an interface
for doing this on Pynamodb table creation, so add that.

Support Streams

---

.gitignore
pynamodb/connection/base.py
pynamodb/connection/table.py
pynamodb/models.py

This is very useful for overriding the size of the Connection Pool and other Session fields.

Configurable Session Class

---

pynamodb/connection/base.py
pynamodb/exceptions.py

Extract the DynamoDB error code from non-200 responses and return it to the caller when throwing Connection Exceptions. This provides a mechanism for the caller to modify their error behavior the error type (e.g. ConditionalCheckFailedException vs InternalServerError).

Return the cause of connection exceptions to the caller.

---

pynamodb/connection/base.py

Previously, when a BatchWriteItem call returned UnprocessedItems, Pynamo
incorrectly assumed that it was a dict of dict of dicts, when it was
actually a dict of list of dicts.

Treat UnprocessedItems as dict of list of dicts

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py

this prevents flaky metadata service from permanently poisoning the `Table` and its `Connection`
fixes #99

regenerate boto client when credentials are None

---

pynamodb/connection/base.py
pynamodb/exceptions.py
pynamodb/tests/test_base_connection.py

Amazon support frequently asks for request ids in support tickets. This makes error messages a little more verbose, adding the table name from the request and the request id from the response.
Example:
> `pynamodb.exceptions.PutError: Failed to put item: An error occurred (ConditionalCheckFailedException) on request (ee416189-1e4f-4911-aef3-1db0a835adf9) on table (MyTable) when calling the PutItem operation: The conditional request failed`

log TableName and RequestId with error messages

---

.gitignore
pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py

Fixes #98. Should alleviate most of the problems users are having in production, though some may still be more comfortable with legacy botocore behavior of retrying on everything. At any rate that will take some more time to implement and come in another PR and should be highly configurable.
This PR does not retry based on status code or error code from DynamoDB. RequestExceptions can be retried quickly without need for exponential backoff and more granular handling so I have implemented it first.
I included private variables with the retry parameters in case someone wants to get at them, but it should  be considered an interface that won't be maintained and might break between minor releases.
TODO:

retry on RequestExceptions only

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_model.py

fixes #125 
- moved binary attribute handling to its own method and added a test for this specific error case
- fixed the test for re-batch_writing unprocessed items since it wasn't doing anything before
worth noting that #97 #114 #120 all got it wrong, at least i think #97 did, the approach is a little different
I read the spec and reimplemented correctly http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html#API_BatchWriteItem_ResponseSyntax

Fix handling of binary attr unprocessed

---

README.rst
docs/tutorial.rst
examples/url_shortener/README.rst
pynamodb/models.py

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py

When writing strings to db do not json encode them.
If they were json encoded, decode them with json. Otherwise just return them.

Serialize UnicodeSetAttributes correctly

---

pynamodb/models.py

Setting log level to info supporesses almost everything.
This feels like one thing that would be useful to see at info level.

Make "unprocessed keys for batch operation" log at info level.

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py

Ref: http://docs.python-requests.org/en/master/user/advanced/
The requests session headers are ignored in the request, if the prepared request object is passed in.
The fix calls requests_session.prepare_request by creating a request object from the aws_request_object
@danielhochman

Fixing the session headers being ignored because of prepared requests

---

docs/conditional.rst
docs/tutorial.rst
examples/model.py
pynamodb/constants.py
pynamodb/models.py
pynamodb/tests/test_model.py

this allows to update multiple attributes at once using a new function `Model.update` (code based on the existing method `Model.update_item()`
This fixes #157 and #195

Multiple attrs update

---

pynamodb/models.py
pynamodb/tests/test_model.py

It should be possible to do:
```py
try:
doStuffWithModels()
except MyModel.DoesNotExist:
print('My model does not exist')  # we'd end up here for MyOtherModel as well
except MyOtherModel.DoesNotExist:
print('My other model does not exist')
```
Currently, `MyModel.DoesNotExist == MyOtherModel.DoesNotExist`. This change makes every model have its own subclass of `pynamodb.exceptions.DoesNotExist`.
btw, this is similar in spirit to what mongoengine does in https://github.com/MongoEngine/mongoengine/blob/3c455cf1c13f923db40de4a855dd402217bee3e1/mongoengine/base/metaclasses.py#L402-L407.

Add distinct DoesNotExist classes per model

---

pynamodb/attributes.py
pynamodb/models.py
pynamodb/tests/test_attributes.py
pynamodb/tests/test_model.py

Defaults were never being set on `MapAttribute`s.
Also removes some complicated type validation logic that was never _actually_ validating types. Leaving that to a future PR, as it's a much larger task.

Ensure defaults are respected for MapAttribute

---

pynamodb/attributes.py
pynamodb/models.py
pynamodb/tests/test_attributes.py
pynamodb/tests/test_model.py

Alternate implementation of https://github.com/jlafon/PynamoDB/pull/213
Note that this changes the semantics of `MapAttribute`s a little such that you will _always_ get back a `MapAttribute` instance when accessing via a parent (Model or MapAttribute) and be required to call `.as_dict()` to convert into a raw dict.
The aim of doing this is consistency -- whether you instantiate a model like `Model(attr={...})` or `Model(attr=MapAttribute())` you should get the same result back when accessing via `model.attr`.
This is a breaking change so we should be sure to document it well in release notes.

Always create map attributes when setting a dict

---

docs/low_level.rst

- Include example for using `update_table` to update ProvisionedThroughput on a Global Secondary Index.
- Use consistent tablename/table_name dummy var.

Small update to API docs: include example for updating ProvisionedThroughput on a GSI

---

pynamodb/connection/base.py

Currently this is a hard failure -- retry with backoff instead. Handling this client side is hard because `batch_write.commit()` clears its list of pending operations on failure.
Related issue: https://github.com/jlafon/PynamoDB/issues/218

Exponential backoff retries for ProvisionedThroughputExceeded errors

---

pynamodb/tests/test_attributes.py

Without keys sorted, an `AssertionError` was being raised on:
```
AssertionError: '{"foo": "bar", "nested": {"nestedfoo": "nestedbar"}, "num": 3}' != '{"num": 3, "foo": "bar", "nested": {"nestedfoo": "nestedbar"}}'
- {"foo": "bar", "nested": {"nestedfoo": "nestedbar"}, "num": 3}
?                                                    ----------
+ {"num": 3, "foo": "bar", "nested": {"nestedfoo": "nestedbar"}}
?  ++++++++++
```

Fix "test_raw_map_json_serialize" when dict ordering differs

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py
requirements.txt
setup.py

No point depending on two libs that provide the same services.

Replace Delorean with dateutil, as dateutil is brought in by botocore

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py

`UTCDateTimeAttribute.deserialize` spends most of it's time inside of dateutil which attempts to first
guess the format.  In most cases PynamoDB will have written the data to begin with, so we can first
optimistically assume the data is stored in DATETIME_FORMAT before falling back to dateutil.
This ~4.5 times faster than always going through dateutil.
```python
from dateutil.parser import parse
import datetime
from dateutil.tz import tzutc
DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%f%z'
now_str = datetime.datetime.now().replace(tzinfo=tzutc()).strftime(DATETIME_FORMAT)
%timeit parse(now_str) # 116 µs ± 9.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit datetime.datetime.strptime(now_str, DATETIME_FORMAT) # 26 µs ± 7.53 µs per loop (mean ± std. dev. of 7 runs, 10000 loops …
```

Speedup UTCDateTimeAttribute deserialization

---

pynamodb/attributes.py
pynamodb/tests/data.py
pynamodb/tests/test_model.py

There was a regression with attribute discovery in https://github.com/pynamodb/PynamoDB/pull/22, where we switched from using `dir(cls)` to `cls.__dict__` to discover attributes. Turns out this doesn't include properties from base classes.

Fix attribute discovery with Model inheritance

---

docs/quickstart.rst
pynamodb/models.py
pynamodb/tests/test_model.py

After being confused by [this logic](https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/models.py#L527-L528), @garrettheel and I thought it would be a good idea to:
+ `raise` if a `count()` is invoked without a `hash_key` AND with a `filter` expression.
+ clarify the `count()` documentation

Raise a ValueError if count() is invoked with no hash key AND filters

---

pynamodb/connection/base.py
pynamodb/constants.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_model.py

This PR is a first step towards moving off of the legacy conditional parameters (#219).
As part of this change, the `attributes_to_get` keyword arguments now support Document Paths:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.Attributes.html
Note that in order to not need special handling for reserved words,
all attributes are replaced with expression attribute name placeholders:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html
Breaking Changes:
Neither `[` nor `]` are allowed characters for attribute names; however, `.` is.
Any attribute names that include a `.` (defined using the `attr_name` keyword argument)
are no longer able to be requested since the name is interpreted as a nested path. …

Replace AttributesToGet with ProjectionExpression / ExpressionAttributeNames

---

pynamodb/attributes.py
pynamodb/connection/base.py
pynamodb/constants.py
pynamodb/expressions/condition.py
pynamodb/expressions/projection.py
pynamodb/expressions/util.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_expressions.py
pynamodb/tests/test_model.py
pynamodb/tests/test_table_connection.py

This PR is a second step towards moving off of the legacy conditional parameters (#219).
With this change, the `key_conditions` query parameter now uses the KeyConditionExpression API.
To support this, this change introduces primitive support for the subset of Condition Expressions required for partition and sort key comparisons along with support for Expression Attribute Values:
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-KeyConditionExpression
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeValues.html
In order to maintain backwards compatibility, the Expression and Condition objects take attribute path and attribute value maps as parameters. To simplify development, helper functions have …

Replace KeyConditions with KeyConditionExpression / ExpressionAttributeValues

---

pynamodb/attributes.py

This lets us remove the MapAttributeMeta metaclass in preparation for adding a metaclass to AttributeContainer to make MapAttribute subclasses behave more like Models.
To illustrate the equivalence, the following snippets show the value of `_attributes` before and after class instantiation before the removal of the metaclass:
```
>>> from pynamodb.attributes import Attribute, MapAttribute
>>> class SubMapAttribute(MapAttribute):
...     a = Attribute()
... 
>>> class SubSubMapAttribute(SubMapAttribute):
...     b = Attribute()
... 
>>> MapAttribute._attributes
{}
>>> print(SubMapAttribute._attributes)
None
>>> print(SubSubMapAttribute._attributes)
None
>>> SubMapAttribute()
<__main__.SubMapAttribute object at 0x1039b7fd0>
>>> SubMapAttribute._attributes
{'a': …
```

Replace the shared _attributes field with a per-subclass fields.

---

pynamodb/attributes.py
pynamodb/expressions/condition.py
pynamodb/expressions/projection.py
pynamodb/expressions/util.py
pynamodb/tests/test_expressions.py

This PR introduces support for both Document Paths and '.' characters in expressions.
Expressions are generated assuming that the path given in the object is a document path;
for example, `Path('foo.bar.baz[0]') == value` is translated into `#0.#1.#2[0] = :0` with the following expression attribute names: `{'#0': 'foo', '#1': 'bar', "#2': 'baz'}`.
With this change, expressions generated from Attribute objects will use whatever attribute name is defined by the `attr_name` field, allowing support for dotted attribute names; for example,
`ListAttribute(attr_name='foo.bar.baz')[0] == value` is translated into `#0[0] = :0` with the following expression attribute names: `{'#0: 'foo.bar.baz'}`.

Support document paths and attribute names containing dot characters.

---

pynamodb/attributes.py
pynamodb/models.py
pynamodb/tests/test_attributes.py

This pull request is a follow-up to https://github.com/pynamodb/PynamoDB/pull/324.
This change moves the `_initialize_attributes` call to the init method of a new metaclass for `AttributeContainer`. The result of this is both `_attributes` and `_dynamo_to_python_attrs` are valid as soon as the class is created as opposed to after the class is first instantiated. Contrast the following code snippet to the examples in the description of the above mentioned pull request.
```
>>> from pynamodb.attributes import Attribute, MapAttribute
>>> class SubMapAttribute(MapAttribute):
...     a = Attribute()
... 
>>> class SubSubMapAttribute(SubMapAttribute):
...     b = Attribute()
... 
>>> MapAttribute._attributes
{}
>>> SubMapAttribute._attributes
{'a': <pynamodb.attributes.Attribute object at …
```

Introduce AttributeContainerMeta

---

pynamodb/attributes.py
pynamodb/expressions/condition.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_expressions.py
pynamodb/tests/test_model.py
pynamodb/tests/test_table_connection.py

This PR is a third step towards moving off of the legacy conditional parameters (#219).
This PR implements the complete operator and function syntax defined for condition expressions:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
In order to support "size" which is both an operand and a function, we make `Path` a subclass of `Operand` and create a special subclass called `Size` just to implement these comparisons.
This change also adds support for primitive values in comparisons (e.g. `size('foo') == 3`).
Note: not all restrictions on the function operands have been enforced and there is no way yet to determine if a given comparison is valid for use in a key condition expression.
Open Question: what is the use case / appropriate …

Support complete condition expression syntax.

---

pynamodb/models.py
pynamodb/tests/test_model.py

From the docs:
"AttributeValueList can contain only one value of type String, Number, or Binary (not a set)."
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.Conditions.html

Bug Fix: the CONTAINS and NOT_CONTAINS operators compare set elements

---

pynamodb/attributes.py
pynamodb/connection/base.py
pynamodb/constants.py
pynamodb/expressions/condition.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_expressions.py
pynamodb/tests/test_model.py
pynamodb/tests/test_table_connection.py

This PR is the fourth step towards moving off of the legacy conditional parameters (#219).
With this change the `conditional_operator `, `expected`, `scan_filter`, and `query_filter` parameters now use the ConditionExpression / FilterExpression API.

Replace Expected / QueryFilter / ScanFilter with ConditionExpresion / FilterExpression

---

pynamodb/connection/base.py
pynamodb/connection/table.py
pynamodb/expressions/condition.py
pynamodb/indexes.py
pynamodb/models.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_model.py
pynamodb/tests/test_table_connection.py

This PR is the sixth step towards moving off of the legacy conditional parameters (#219).
With this change `query` and `scan` now take additional keyword args for `range_key_condition` (query only) and `filter_condition`.
Using legacy filter parameters will emit a warning. Using both condition expressions and legacy parameters will raise a ValueError.
Note: The legacy filter parameters allow some invalid commands to be created. The new parameters correctly detect invalid commands and raise a ValueError.

Query and Scan Filters using Condition Expressions

---

pynamodb/connection/base.py
pynamodb/constants.py
pynamodb/expressions/update.py
pynamodb/tests/test_base_connection.py
pynamodb/tests/test_expressions.py
pynamodb/tests/test_model.py
pynamodb/tests/test_table_connection.py

This PR introduces a translation from the legacy attribute update syntax to update expressions.
It is just a "complete enough" implementation in order to make update commands functional.
Further work is required to provide proper low-level and high-level APIs that tie into the "Path" and "Attribute" objects. This is purely an initial step given that the exact design of those APIs is not yet complete.

Replace AttributeUpdates with UpdateExpression

---

pynamodb/attributes.py
pynamodb/models.py
pynamodb/tests/test_attributes.py

This PR attempts to provide parity between "raw" MapAttributes and MapAttribute subclasses.
MapAttribute subclasses can set bound attribute values using the Attribute data descriptors.
Prior to this change, "raw" MapAttribute instances could only set name-value pairs during initialization.
With this change, all MapAttribute instances are instantiated as AttributeContainers and can access data stored on the internal attribute_values dictionary (either via the __getattr__ and __setattr__ methods in the case of "raw" MapAttributes, or via the Attribute data descriptors in the case of subclasses).
MapAttribute instances that are class objects of other AttributeContainers (Models or other MapAttribute subclasses) are "re-initialized" as Attributes by AttributeContainerMeta during class …

Support setting attributes on "raw" MapAttribute instances.

---

pynamodb/attributes.py
pynamodb/connection/base.py
pynamodb/expressions/condition.py
pynamodb/expressions/projection.py
pynamodb/expressions/update.py
pynamodb/expressions/util.py
pynamodb/models.py
pynamodb/tests/test_attributes.py
pynamodb/tests/test_expressions.py

This commit adds support for creating condition expressions from nested attributes.
Consider the following model definition:
```
>>> class MyMap(MapAttribute):
...     ua = UnicodeAttribute(attr_name='str_attr')  
... 
...     class Meta:
...         table_name='foo'
...     my_map = MyMap(attr_name='map_attr')
... 
```
Without this change, condition expressions did not include the document path:
```
>>> MyModel.my_map.ua == 'baz'
str_attr = baz
```
With this change, the condition expression correctly constructs the document path:
```
>>> MyModel.my_map.ua == 'baz'
map_attr.str_attr = baz
```
When initializing AttributeContainer class objects, any MapAttribute instances in the attribute list now make local copies of their class attributes. Using the above …

Support MapAttribute map dereferencing in condition expressions.

---

pynamodb/expressions/condition.py
pynamodb/expressions/operand.py
pynamodb/expressions/update.py
pynamodb/tests/test_expressions.py

This commit extends the expression api to always allow attribute names and values as operands:
```
>>> from pynamodb.expressions.operand import Path, Size
>>> Path('foo') == Path('bar')
foo = bar
>>> Size('foo') != Size('bar')
size(foo) <> size(bar)
```

Expression operands can be attribute names or attribute values.

---

docs/conditional.rst
pynamodb/attributes.py
pynamodb/expressions/operand.py
pynamodb/tests/test_expressions.py

This commit adds support for creating condition expressions for nested map attributes using Python's item operator: `[]`
Consider the following item definition:
```
>>> class MyMap(MapAttribute):
...     ma = MapAttribute(attr_name='raw')
... 
...     class Meta:
...         table_name='foo'
...     my_map = MyMap(attr_name='map_attr')
```
Without this change, condition expressions cannot be created for nested attributes of `ma`:
```
>>> MyModel.my_map.ma.foo == 'bar'
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "pynamodb/attributes.py", line 680, in __getattr__
raise AttributeError("'{0}' has no attribute '{1}'".format(self.__class__.__name__, item))
AttributeError: 'MapAttribute' has no attribute 'foo'
```
With this change, …

Support "raw" MapAttribute dereferencing in condition expressions.

---

pynamodb/attributes.py
pynamodb/expressions/operand.py
pynamodb/tests/test_attributes.py

Now that we support nested element access in condition expressions using Python's `__getitem__` operator, Attributes are considered iterables (see PEP 234).
This commit prevents `iter()` calls on attributes (except for MapAttributes that are being used as AttributeContainers).
In addition, we add support for item assignment to MapAttributes to be symmetric with item access.

Better handling of MapAttribute iteration and item assignment.

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py

Models do not serialize null attributes. MapAttributes should not serialize them either.

Don't serialize null nested attributed. Fixes #240 and #309

---

pynamodb/models.py
pynamodb/pagination.py
pynamodb/tests/test_model.py

This commit replaces the model's scan and query generator functions with an iterator object.
This address issues #50, #118, and #207.
The object exposes a `last_evaluated_key` property which allows the caller to perform pagination while using the high-level API:
```
results = []
started = False
last_evaluated_key = None
while not started or last_evaluated_key is not None:
started = True
results_iter = UserModel.query('foo', limit=50)
results.append(list(results_iter))
last_evaluated_key = results.last_evaluated_key
```

Support pagination in high-level api query and scan methods.

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py

As described in the docs, the response from batch get looks like so:
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html#DDB-BatchGetItem-response-UnprocessedKeys
```
"UnprocessedKeys": {
"string" : {
"AttributesToGet": [ "string" ],
"ConsistentRead": boolean,
"ExpressionAttributeNames": {
"string" : "string"
},
"Keys": [
{
"string" : {
"B": blob,
"BOOL": boolean,
"BS": [ blob ],
"L": [
"AttributeValue"
],
"M": {
"string" : "AttributeValue"
},
"N": "string",
"NS": [ "string" ],
"NULL": boolean,
"S": "string",
"SS": [ "string" ]
}
}
],
"ProjectionExpression": "string"
}
}
```
This fix accounts for the keys being in the table's dict under the key 'Keys'
Another pull request for the same issue: #253
Fixes #252

Handle values from keys when batch get returns unprocessed keys

---

pynamodb/constants.py
pynamodb/pagination.py
pynamodb/tests/test_model.py

Support limiting the total number of items evaluated by a query or scan operation (replaces #315).
This gives users better control over the capacity consumed by these operations, e.g.:
```
class PageLimitedIterator(object):
def __init__(self, page_iterator, max_scanned_count):
self._iter = page_iterator
self._max_scanned_count = max_scanned_count
def __iter__(self):
return self
def __next__(self):
limit = self._max_scanned_count - self._iter.total_scanned_count
if limit == 0:
raise StopIteration()
if limit < self._iter.page_size:
self._iter.page_size = limit
return next(self._iter)
def next(self):
return self.__next__()
result_iterator = Model.scan()
result_iterator.page_iter = PageLimitedIterator(result_iterator.page_iter, 10)
for item in result_iterator:
```

Support limiting the total number of items evaluated by a query or scan operation.

---

pynamodb/pagination.py
pynamodb/tests/test_model.py

The recent addition of PageIterator in #395 has muted the `last_evaluated_key` to query and scan methods.
This prevents manually getting results for a specific page.

Fix exclusive_start_key getting lost in PageIterator

---

.travis.yml

Ubuntu still defaults to 3.5 for python 3.x.

Add python 3.5 for Travis ci builds

---

docs/awsaccess.rst
pynamodb/connection/table.py
pynamodb/models.py
pynamodb/tests/test_model.py
pynamodb/tests/test_table_connection.py

Hi! I'm currently working with microservice using Zato and we have all of our config settings in a specific place (not the same as the default files expected by botocore). We have made our integration with Dynamo using boto3 (because it allows us to set the AWS credentials when we create a session) but we are looking forward to migrate to PynamoDB and setting the credentials on the fly is a requirement...
For this, I externalized the AWS credentials attributes in the Model's MetaClass and passed them along to the TableConnection to set the session credentials. This solution works for me and now I'm using this forked version. I decided to open this PR as a way to discuss if this is a valid solution or if we could improve it (I'm not a dynamo expert whatsoever). Let me know your thoughts! 😃

Externalizes AWS Credentials

---

pynamodb/attributes.py
pynamodb/models.py
pynamodb/tests/integration/test_migration.py

Change update & update_item to use attr.get_value(value) in deserialization.
The PR https://github.com/pynamodb/PynamoDB/pull/149 introduced ```attr.get_value(value)``` for backward compatibility between LBA and BA, and used it in ```model.from_raw_data ``` but not in ```model.update_item``` (nor ```model.update```) causing code like https://gist.github.com/betamoo/1fb15692d6fa74b9ddacfd4965632b26 to fail

Use attr.get_value(value) when deserialize

---

pynamodb/attributes.py
pynamodb/expressions/operand.py
pynamodb/tests/test_expressions.py

The expression classes assume that whenever an attribute appears in the right hand side argument that the resulting expression should use the attribute's path. That allows users to compare two attributes of an item or to update one attribute of the item based on another. For example:
```
...     foo = UnicodeAttribute()
...     bar = UnicodeAttribute()
...
>>> MyModel.foo > MyModel.bar
foo > bar
>>> MyModel.foo.set(MyModel.bar)
foo = bar
```
However, the code failed to consider that some attribute classes, specifically MapAttribute and its subclasses, can sometime act as AttributeContainer objects depending on the context. When instantiated as an attribute container, the instance should behave as a Value in the right hand side of an expression:
```
>>> class …
```

Allow MapAttribute instances to be used as the RHS in expressions.

---

pynamodb/attributes.py
pynamodb/models.py

Being able to dynamically introspect Model classes is valuable for tasks
such as validation. This commit converts the underscore-prefixed private
method `_get_attributes` into a public method.

Make get_attributes public

---

docs/updates.rst

It is important that the default is not mutable, because that would cause the default value to be modified when the first instance of the object is modified.  
The current example results in following behaviour
```python
thread = Thread()
thread.notes.append('First note')
empty_thread = Thread()
empty_thread.notes
>>> ['First note']
```

Fix faulty documentation example

---

pynamodb/pagination.py

Hello, 
`im_self` doesn't exists anymore in python 3 (https://docs.python.org/2/reference/datamodel.html). So using six to fix this.
Saw this happen multiple times in production. Sorry though I can't seem to redo it in unit test without messing with the internal state of the ResultIterator (e.g. by making `results_iter._index=1` so it is different from count after the iterator is fully consumed).
Thanks for this package !

Fix Python 3 compatibility of PageIterator#key_names

---

MANIFEST.in
setup.cfg

The MIT license requires all copies of the program to include a copy of the license.  Also include some other useful files in sdists.

Include license and other files in sdists and wheels

---

setup.py
tox.ini

This small PR updates the python versions in the `tox.ini` file and `setup.py` file. 
I noticed some inconsistencies between the versions supported in the files with the current supported versions in the `.travis.yml` content (which seems to support `py36` unless I'm missing something). I'm not sure if that's intended or not. I think this would bring more consistency to the code base. 
Any comments more than welcome !

Updates setup.py and tox.ini to reflect supported python versions

---

setup.py

This is required to ensure that `.pyi` files end up in packages. `find_stubs` via https://github.com/numpy/numpy-stubs/blob/master/setup.py

Fix type stub packaging

---

pynamodb/models.pyi
pynamodb/tests/test_mypy.py

This allows constructs like:
```py
def query_with_status(key, status):
return MyModel.query(
hash_key=key,
filter_condition=(MyModel.status == status) if status else None,
)
```

Model.query: conditions are optional

---

requirements-dev.txt

pyyaml 5.1 deprecated Python 2.6 support: https://pyyaml.org/wiki/PyYAML

requirements-dev: pin PyYAML fo Python 2.6

---

docs/batch.rst

The batch operations docs were using the `TestModel` class which is not explained in this section of the docs. I believe the example code was supposed to use the `Thread` class anyway so I have updated it accordingly.

fix batch operations docs to use the Thread model in the example code

---

pynamodb/attributes.py
pynamodb/tests/test_attributes.py

This optimization speeds up parsing UTCDateTimeAttribute's written by Pynamodb (the vast majority of cases) 5x in Python 3, 38x in Python 2 (Python 2 doesn't support `%z`).
While this code is a bit of a hack, it will significantly speed up what is our long poll in deserialization.

Add a fastpath parser to UTC formatted datestrings

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py

Putting this up for discussion to include in the 4.0.0 release. I poked around a little at some performance regressions that I've noticed with recent pynamodb+botocore combinations, and this seems to be mostly due to growing complexity around signing requests. In particular, liberal use of the hook system [1] adds a lot of unnecessary work to the critical path
There may be some other opportunities to optimise here, but this seems like the largest to begin with. The downside of this change is that changes to `RequestSigner` or the owning `BaseClient` in a future `botocore` release may cause breakage, however I don't think this worsens the current state much.
[1] https://github.com/boto/botocore/blob/cf8d3bb149d599eef12ce31c30b21c6fb9ad217b/botocore/hooks.py#L390

Bypass most unnecessary botocore logic surrounding auth

---

docs/requirements.txt
requirements-dev.txt

We're no longer supporting Python 2.6.

unpin Python 2.6 dependencies

---

pynamodb/connection/base.py
pynamodb/tests/test_base_connection.py

`Connection.query` raises `ValueError("No hash key attribute for index: {}".format(index_name))` if it cannot find the hash key name for a given index. I interpret this error as the index exists, but there is an issue with the hash key. What is really happening is either 1. the index does not exist 2. the index exists, but it does not have a hash key attribute. In case 1, we should raise an exception that is explicit about the fact the index does not exist.

raise better error message when index does not exist

---

pynamodb/expressions/condition.py
pynamodb/tests/test_expressions.py

This change attempts to allow users to more easily chain condition statements:
```
condition = None
if (foo):
condition &= foo_condition
if (bar):
condition &= bar_condition
if (baz):
condition &= baz_condition
```

Allow None to be used to bootstrap condition chaining.

---

pynamodb/attributes.py

When creating models for a already existing database, The ```UTCDateTimeAttribute``` fails to deserialise a date in the format ```2019-07-01T00:00:00``` because it doesn't have the tzinfo, example:
```
File “.../versions/3.7.0/lib/python3.7/site-packages/pynamodb/attributes.py”, line 897, in _fast_parse_utc_datestring
datestring[13] != ‘:’ or datestring[16] != ‘:’ or datestring[19] != ‘.’ or
IndexError: string index out of range
```
In previous versions of pynamodb it was working, so I'm proposing this fix.

Catch IndexError when trying to fast parse a date time  string value

---

pynamodb/attributes.py
tests/test_attributes.py
tests/test_model.py

Allows specifying `timedelta`s in expressions involving TTLAttribute:
```py
class MyModel(Model):
...
ttl = TTLAttribute()
model = MyModel()
model.update(actions=[
MyModel.ttl.set(timedelta(days=42)),
])
```

Allow TTLAttribute.set with timedelta

---

AUTHORS.rst
docs/optimistic_locking.rst
examples/optimistic_locking.py
pynamodb/attributes.py
pynamodb/attributes.pyi
pynamodb/connection/base.py
pynamodb/models.py
pynamodb/transactions.py
tests/data.py
tests/integration/model_integration_test.py
tests/integration/test_transaction_integration.py
tests/test_attributes.py
tests/test_model.py
tests/test_transaction.py

Adds a new nullable version attribute type which initializes at 1 and increments on save/update for optimistic locking.

Support for versioned optimistic locking a la DynamoDBMapper

---

pynamodb/connection/base.py
pynamodb/models.py

Fixes below error + makes GSIs inherit the billing mode of the parent table correctly
```
Traceback (most recent call last):
File "test_ddb.py", line 25, in <module>
TestModel.create_table(wait=True)
File "/Users/ed.holland/repos/PynamoDB/pynamodb/models.py", line 732, in create_table
**schema
File "/Users/ed.holland/repos/PynamoDB/pynamodb/connection/table.py", line 283, in create_table
billing_mode=billing_mode
File "/Users/ed.holland/repos/PynamoDB/pynamodb/connection/base.py", line 631, in create_table
raise TableError("Failed to create table: {}".format(e), e)
pynamodb.exceptions.TableError: Failed to create table: An error occurred (ValidationException) on request (78S7ALQ39N25306KJDNBE18LIBVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (test_table) when calling the CreateTable operation: One …
```

Remove PROVISIONED_THROUGHPUT objects for GSIs on PAY_PER_REQUEST tables

---

.travis.yml
requirements-dev.txt
tests/response.py
tox.ini

this does a couple of important things:
- upgrade `pytest` so the `imp` warning is visible
- unpin direct dependencies (this ensures testing against the latest versions possible to expose breakages as soon as possible)
- replace `requests` with `urllib3` (`botocore` doesn't use `requests` any more)

unfloat versions to expose warnings

---

pynamodb/connection/base.py

The exceptions we raise off botocore exceptions contain all the required information, so chaining the botocore exception (in Python 3) just results in noisier logs.

Prevent exception chaining

---

setup.py

We're still testing against Python 3.5 in .travis.yml so we might as well classify with it?

Update PyPI classifiers (production, py3.5)

---

AUTHORS.rst
MANIFEST.in
docs/contributing.rst

There are many authors not listed and here and the file is out of date, so let's just remove it.

Remove AUTHORS.md

---

pynamodb/connection/base.py

In moving to botocore in 4.0, we're spending unnecessary time validating parameters that we weren't previously doing. Given that pynamodb already does parameter validation, I don't think there's a ton of value in doing this so let's turn it off for performance reasons.

Disable botocore parameter validation

---

requirements-dev.txt

This is mostly to fix the docs build, which is failing due to https://github.com/boto/botocore/issues/1872

Bump dev dependencies

---

pynamodb/connection/base.py
tests/test_base_connection.py
tests/test_model.py
tests/test_table_connection.py

DynamoDB in some AZs (e.g. ap-northeast-3) does not support the BillingMode parameter (and any billing modes other than 'provisioned'). We'll avoid sending BillingMode if it is 'provisioned'.

Do not pass BillingMode: ‘PROVISIONED’ to CreateTable

---

pynamodb/_compat.py
pynamodb/settings.py

This PR uses `importlib` rather than the deprecated module `imp` for loading modules from a path. 
The error that this PR addresses is a pytest DeprecationWarning:
`
/lib/python3.7/site-packages/pynamodb/settings.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
`

use importlib instead of deprecated library imp

---

pynamodb/connection/base.py
pynamodb/models.py
tests/test_model.py

There is currently a problem with exponential backoff for batch write requests.
This is because a batch that exceeds provisioned capacity does not return an error code that can be caught in https://github.com/pynamodb/PynamoDB/blob/28b3a4589fdc00868e902864d1ab6552f782f545/pynamodb/connection/base.py#L441-L466 code block, but instead returns a success code with an object describing the failing records.
This PR introduces sleep time + a max retry limit to the existing batch write loop.
Additionally it saves the state of failed records when failing so the client can retry these records if needed. This resolves some comments in #218

Implement exponential backoff for batch writes

---

pynamodb/indexes.py
pynamodb/indexes.pyi

This was accidentally missed in https://github.com/pynamodb/PynamoDB/pull/632, but passing `**filters` would currently raise an error since the `Model` functions don't take **kwargs anymore. Also cleaned up stubs and made sure the indexes are compatible with the model function signatures

Remove conditional APIs from indexes

---

pynamodb/models.py
tests/test_model.py

If an `UpdateItem` removes an attribute on an item in the db, this update is not reflected on the in memory object after the request succeeds.
We request `RETURN_VALUES` as `ALL_NEW` during an [update](https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/models.py#L383). DynamoDB will return the current state of all attributes as `Attributes` in the response.
Before this PR, we iterate over all of the returned attributes and assign them to the in memory copy of the item. This fails to account for an attribute that was removed via the `UpdateItem` request e.g.
```python
>>> item = SomeModel.get('foo')
>>> print(item.some_attribute)
'attribute_value'
>>> item.update(actions=[SomeModel.some_attribute.remove()]
>>> print(item.some_attribute)
'attribute_value'
```
In this PR, we leverage …

ensure Model.update accounts for REMOVE expressions on in memory object

---

docs/release_notes.rst
pynamodb/__init__.py
pynamodb/indexes.pyi
pynamodb/models.pyi
requirements-dev.txt
tests/test_mypy.py

This now works again:
```python
from pynamodb.attributes import NumberAttribute
from pynamodb.models import Model
from pynamodb.indexes import GlobalSecondaryIndex
from pynamodb.pagination import ResultIterator
class UntypedIndex(GlobalSecondaryIndex):
bar = NumberAttribute(hash_key=True)
class MyModel(Model):
foo = NumberAttribute(hash_key=True)
bar = NumberAttribute()
untyped_index = UntypedIndex()
untyped_result: ResultIterator = MyModel.untyped_index.query(123)
model: MyModel = next(untyped_result)
not_model: int = next(untyped_result)  # this is legacy behavior so it's "fine"
```
and then this is also possible now:
```python
class TypedIndex(GlobalSecondaryIndex[MyModel]):
bar = NumberAttribute(hash_key=True)
class MyModel(Model):
foo = NumberAttribute(hash_key=True)
bar = …
```

Fix Index.query and Index.scan typing issues

---

pynamodb/_compat.py

This is breaking tests on new PRs, so ignoring this false positive for now.

Fix type error on SourceFileLoader.load_module

---

pynamodb/models.pyi
tests/test_mypy.py

This is needed to correctly type lookups for keys that use `UTCDateTimeAttribute`, and future-proof further changes

Change `KeyType` to use `Any`

---

docs/attributes.rst

This was a simple typo, the documentation was pointing to the "devel" branch before.

Point Map Attributes example to master branch

---

setup.py

This change adds `tests.integration` to the excluded packages

Issue #757 - fix for setup.py

---

docs/release_notes.rst
pynamodb/__init__.py
pynamodb/_compat.py
pynamodb/indexes.py

Following 5426ed9081e91316b214d6c10b447cfa1da8b0af, users found themselves having to write some rather unergonomic code to reconcile Python's and a type-checker's perspectives:
```python
if TYPE_CHECKING:
_MyModelGSI = GlobalSecondaryIndex["MyModel"]
else:
_MyModelGSI = GlobalSecondaryIndex
class MyModelUserIdGSI(_MyModelGSI):
"""A GSI for looking up by user ID."""
...
class MyModelEmailGSI(_MyModelGSI):
"""A GSI for looking up by email."""
...
```
This addresses it by allowing users to rewrite this as:
```python
class MyModelUserIdGSI(GlobalSecondaryIndex["MyModel"]):
"""A GSI for looking up by user ID."""
...
class MyModelEmailGSI(GlobalSecondaryIndex["MyModel"]):
"""A GSI for looking up by email."""
...
```
Since we maintain Python 2 compatibility, we cannot assume the typing module is …

Make (GS,LS)Index a Generic in runtime

---

requirements-dev.txt
tests/conftest.py
tests/mypy_helpers.py
tests/test_mypy.py

- improved mypy-testing integration:
(a) mypy crashes and failed assertions now result in a stack trace
(b) `pytest --pdb` now propagates to `mypy --pdb`
(c) turning on type error codes for even more fidelity
- 'reveal_type' now results in NOTICE-level messages so updating tests accordingly 
- turned on type error codes, updated tests accordingly
- `assert_mypy_output` is now available (and used) as a fixture so it could rely on the `pytestconfig` fixture to get pytest config state

update mypy tests

---

requirements-dev.txt

travis-ci's venv seems to come with pytest installed (?!) which causes a newer version not to be installed, and pytest-cov recently bumped their min pytest version.

require pytest>=5

---

pynamodb/exceptions.py
pynamodb/models.py
tests/test_model.py

When deserialization error occurs in `from_raw_data`, it's unclear which attribute it is failing on. Add attribute name in exception

More context in exception on attr deserialization failure

---

pynamodb/attributes.py

This fixes a "bug" where attributes without custom names are added to the mapping in MapAttribute sub-subclasses.
```
MyMap(MapAttribute):
foo = StringAttribute()
MySubMap(MyMap):
pass
```
With this change `foo` is no longer added to `MySubMap._dynamo_to_python_attrs`

Only add custom attribute names to the mapping.

---

pynamodb/attributes.py
tests/test_attributes.py
tests/test_model.py

This change removes python 2 support, the `SetMixin` class, the unnecessary sorting during serialization.

Simplify set attribute serialization/deserialization.

---

docs/release_notes.rst
docs/updates.rst
pynamodb/attributes.py
pynamodb/expressions/operand.py
pynamodb/expressions/update.py
tests/test_expressions.py

This reverts commit a5f2369a3684ca12c1abd16d786ec4f82c6b9a24.
Removal of list elements is already supported using the path expression syntax.

Revert "Support removing specific indexes from a ListAttribute (#754)"

---

pynamodb/attributes.py
tests/test_attributes.py
tests/test_expressions.py

Return properly configured attributes when accessing typed list attribute elements to enable accessing nested elements.
Consider the following list of maps:
```
from pynamodb.attributes import  ListAttribute, MapAttribute,UnicodeAttribute
from pynamodb.models import Model
class StringMap(MapAttribute):
bar = UnicodeAttribute()
class MyModel(Model):
foo = UnicodeAttribute(hash_key=True)
maps = ListAttribute(of=StringMap)
```
With this change it is now possible to write expressions that reference the embedded `bar` attribute:
```
>>> MyModel.maps[0].bar.exists()
attribute_exists (maps[0].bar)
```
Previously this would raise an exception:
```
>>> MyModel.maps[0].bar.exists()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'Path' object has no attribute …
```

Improve typed list attribute expression creation.

---

pynamodb/attributes.py
pynamodb/models.py
tests/test_attributes.py

Currently when serializing MapAttribute subclasses, only attributes defined in the type being serialized are written.
```
>>> from pynamodb.attributes import ListAttribute, MapAttribute, UnicodeAttribute
>>> from pynamodb.models import Model
>>> class SuperclassMap(MapAttribute):
...     bar = UnicodeAttribute()
... 
>>> class SubclassMap(SuperclassMap):
...     baz = UnicodeAttribute()
... 
...     foo = UnicodeAttribute(hash_key=True)
...     map = SuperclassMap()
...     list = ListAttribute(of=SuperclassMap)
... 
>>> subclass_map = SubclassMap(bar='bar', baz='baz')
>>> MyModel(foo='foo', map=subclass_map, list=[subclass_map])._serialize()
{'attributes': {'list': {'L': [{'M': {'bar': {'S': 'bar'}, 'baz': {'S': 'baz'}}}]}, 'map': {'M': {'bar': {'S': 'bar'}}}}, …
```

Enable polymorphism by serializing all attributes in subclasses.

---

pynamodb/connection/base.py
tests/integration/test_transaction_integration.py

The current error messaging does not include table names when an exception is encountered during a transaction. This change provides a sequential list of all tables on which a transactional operation was attempted. Please note that the purpose of including table names is to enable human debugging without causing confusing (like in https://github.com/pynamodb/PynamoDB/issues/816).

Add table name to error message for transactional operations

---

docs/release_notes.rst
pynamodb/attributes.py
requirements-dev.txt
setup.py
tests/test_attributes.py

This removes the dependency on `python-dateutil`.

UTCDateTimeAttribute now requires the date string format '%Y-%m-%dT%H:%M:%S.%f%z'.

---

pynamodb/connection/table.py
pynamodb/models.py
tests/test_model.py

This is very much an incomplete hack. This will support the use case in #361 for models with different tables;
however, inheritance of the same table but with other attributes differing (e.g. region) are still not supported.

Partial support for model inheritence backed by different tables. Fixes #361

---

pynamodb/models.py
tests/test_model.py
tox.ini

This PR will allow PynamoDB to read & update historical data (persisted using another python client library) whose initial version value is less than 1. 
Currently, `version = 0` is [treated the same](https://github.com/pynamodb/PynamoDB/blob/b42c326529f9043bafccf334eaa0c16ac610d795/pynamodb/models.py#L939) as `version = None`: PynamoDB will add [does_not_exist condition check](https://github.com/pynamodb/PynamoDB/blob/b42c326529f9043bafccf334eaa0c16ac610d795/pynamodb/models.py#L948) when persisting to DynamoDB and this leads to `ConditionalCheckFailedException` as the item already exists.

Allow VersionAttribute to operate on items with a version of zero

---

pynamodb/connection/base.py

When we get a `TransactionCanceledException` error on the API the
response text is in the following format:
```
{
"CancellationReasons": [
{
"Code": "ConditionalCheckFailed",
"Message": "The conditional request failed"
}
],
"Message": "Transaction cancelled, please refer cancellation reasons for specific reasons [ConditionalCheckFailed]",
"__type": "com.amazonaws.dynamodb.v20120810#TransactionCanceledException"
}
```
As we only look up the `message` key we get the following error, which doesn't allow us to tell the difference between different types of `TransactionCanceledException`.
```
{'Error': {'Message': '', 'Code': 'TransactionCanceledException'}}
```
Weirdly `amazon/dynamodb-local` returns the same but with the key as `message`:
```
{
"CancellationReasons": [
{
"Code": …
```

Fallback to `Message` if `message` is missing from >= 300 responses

---

docs/release_notes.rst
mypy.ini
pynamodb/__init__.py
pynamodb/attributes.py
pynamodb/models.py
tests/test_mypy.py

Doing this:
```python
from pynamodb.attributes import MapAttribute
class MyMap(MapAttribute, object):  # <-- location of type error
pass
```
would result in the following errors from mypy:
```
error: Definition of "__eq__" in base class "Attribute" is incompatible with definition in base class "AttributeContainer"
error: Definition of "serialize" in base class "Attribute" is incompatible with definition in base class "AttributeContainer"
```
The error is not shown in the simpler form:
```python
class MyMap(MapAttribute):
pass
```
https://github.com/python/mypy/issues/10066

Fix type errors when deriving from a MapAttribute and another type

---

docs/release_notes.rst
pynamodb/__init__.py
pynamodb/models.py
pynamodb/transactions.py
tests/integration/model_integration_test.py
tests/test_model.py

Not only it is more efficient not to serialize attributes you don't need, it also manifested in an issue where an `update` operation would fail null-checks on attributes that are not even affected by the update -- see added `test_update_doesnt_do_validation_on_null_attributes` test.
p.s. this uncovered another bug where we fail to propagate `null_checks=True` through MapAttributes, but we'll address it separately

Do not serialize all attributes for updates and deletes

---

docs/release_notes.rst
pynamodb/__init__.py
pynamodb/attributes.py
tests/test_model.py

Before this change, the Model would propagate null_check to the immediate MapAttributes but then those MapAttributes wouldn't propagate it to deeper-nested ones.
P.S. In practice we're not using `null_check` anymore, since we're no longer calling `get_save_args` for non-save. We used to pass `null_check=False` to prevent updates tripping on unrelated null attributes but it's not needed since #905. It is part of the API though.

Propagate null_check flag when serializing nested MapAttributes

---

docs/release_notes.rst
pynamodb/attributes.py
pynamodb/exceptions.py
pynamodb/models.py
tests/test_model.py

This would make it easier to understand errors when a nested field is left unset.

Null errors should include full attribute path

---

pynamodb/models.py

"on_demad" looks as a value that should be set, but it's not

improve doc string for create_table

---

pynamodb/models.py
tests/test_model.py

Workaround to avoid triggering server validation error:
```json
{
"Error": {
"Message": "Provided list of item keys contains duplicates",
"Code": "ValidationException"
}
}
```
This doesn't update the underlying `connection.Table` or `connection.Base` `batch_get_item` call.

Wrap `items` in a `set` call for `Model.batch_get`

---

docs/attributes.rst
pynamodb/attributes.py
tests/test_attributes.py
tests/test_discriminator.py

DynamicMapAttribute is a map attribute that supports declaring attributes (like an AttributeContainer),
but will also store any other values that are set on it (like a raw MapAttribute).
This class lets you create a "partially typed" map attribute so that it can store items that are not just primitive python types.
```
>>> from datetime import datetime
>>> from pynamodb.attributes import DynamicMapAttribute
>>> from pynamodb.attributes import UTCDateTimeAttribute
>>> from pynamodb.models import Model
>>> 
>>> class CreatedAtMap(DynamicMapAttribute):
...     created_at = UTCDateTimeAttribute()
... 
...     my_map = CreatedAtMap(default={})
... 
>>> my_model = MyModel()
>>> my_model.my_map.created_at = datetime.utcnow()
>>> my_model.my_map.foo = 'bar'
>>> …
```

Introduce DynamicMapAttribute

---

pynamodb/models.py

This is a preliminary change to simplify index management before fixing #992.

Initialize indexes in the model metaclass.

---

pynamodb/transactions.py
tests/test_mypy.py

This should fix #916, as the __enter__ method now returns the correct subclass from which it was called.
I created a testcase to mypy tests, but I think it's not really testing anything yet. I would be glad to get help on proper test implementation.

Add generic self type hint to Transaction

---

pynamodb/indexes.py
pynamodb/models.py
tests/test_model.py

Currently we require indexes to define the hash and range keys using attributes that hopefully match the model definition.
This change begins to unwind this dependency by using the Model attribute definitions to generate the create table schema.

Always use Model attribute definitions in create table schema.

---

pynamodb/attributes.py
pynamodb/indexes.py
pynamodb/models.py

Set attribute names using the python 3.6+ `__set_name__` function that is called during AttributeContainer class creation.
This simplifies MapAttribute classes slightly since we can check once if an instance is an AttributeContainer class attribute.

Use PEP-487 __set_name__ to simplify the Model and Index metaclasses.

---

docs/release_notes.rst
pynamodb/attributes.py
pynamodb/models.py
pynamodb/util.py
tests/test_attributes.py
tests/test_model.py

Model instances now support two types of serialization:
- `serialize/deserialize` can be used to convert models to DynamoDB AttributeValue dictionaries
- `to_json/from_json` can be used to convert models to JSON strings

Add support for JSON serialization.

---

docs/release_notes.rst
pynamodb/indexes.py
pynamodb/models.py

This is a breaking change to the index API. The count, query, and scan methods are now instance methods.

Store Model class reference on an instance of index class. Fixes #992

---

pynamodb/attributes.py
tests/test_expressions.py

This commit makes two backwards incompatible changes.
- Attribute equality comparisons now return condition expressions instead of boolean values and attempting to treat them as a boolean raises a TypeError:
```
>>> from pynamodb.attributes import UnicodeAttribute
>>> UnicodeAttribute(attr_name='foo') == UnicodeAttribute(attr_name='bar')  # used to return `False`
foo = bar
>>> bool(UnicodeAttribute(attr_name='foo') == UnicodeAttribute(attr_name='bar'))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/jpinner/workspace/PynamoDB/pynamodb/expressions/condition.py", line 49, in __bool__
raise TypeError("unsupported operand type(s) for bool: {}".format(self.__class__.__name__))
TypeError: unsupported operand type(s) for bool: Comparison
```
- MapAttribute …

Improve condition expression support for attribute comparisons. Fixes #508

---

pynamodb/__init__.py

With https://github.com/pynamodb/PynamoDB/pull/995 and other breaking changes about to enter, we should bump the version so we won't accidentally release them under 5.x.

Bump version to 6.0 pre-release

---

docs/release_notes.rst
pynamodb/__init__.py

Backports https://github.com/pynamodb/PynamoDB/pull/1018 into a 5.2.1 release
See https://github.com/pynamodb/PynamoDB/commits/backport-1018-5.x

Prepare for 5.2.1 release

---

pynamodb/transactions.py
tests/test_mypy.py

`TransactGet` can be used to fetch different Models in the same transaction, but because the `_M` was bound to the instance it was not possible to type such code correctly. I think `TransactGet` should be typed the same way as `TransactWrite`.
Additionally, I added typing to `__init__` to prevent _Call to untyped function in typed context_

Fix typing on TransactGet

---

pynamodb/connection/__init__.py

When running `mypy` in strict mode I got this error:
```
error: Module "pynamodb.connection" does not explicitly export attribute "Connection"; implicit reexport disabled  [attr-defined]
```

Add explicit export to connection to fix mypy error

---

pynamodb/attributes.py
tests/test_model.py

Follow up to #915:
- Nested maps
- Lists

Null errors should include full attribute path for lists

---

examples/model.py

There were two issues:
* The positional condition expression in `Thread.query` was being treated as a `range_key_condition` instead of a `filter_expression`
* `thread_item.delete()` was being called before updates occurred, causing errors due to the item not existing

Fix models example code

---

docs/contributing.rst
docs/quickstart.rst
docs/rate_limited_operations.rst
docs/signals.rst
docs/tutorial.rst

There are small typos in:
- docs/contributing.rst
- docs/quickstart.rst
- docs/rate_limited_operations.rst
- docs/signals.rst
- docs/tutorial.rst
Fixes:
- Should read `scanning` rather than `scaning`.
- Should read `overridden` rather than `overidden`.
- Should read `identifier` rather than `identifer`.
- Should read `deserializing` rather than `deserializng`.
- Should read `auxiliary` rather than `auxillary`.
- Should read `attributes` rather than `attributues`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

pynamodb/models.py

The existing to_json and from_json functions already handled everything necessary for to_dict and from_dict, so this ends up being a fairly trivial change. 
I believe existing tests for to_json and from_json will exercise these changes adequately. 
Should solve #1031

Model: add to_dict and from_dict

---

pynamodb/connection/_botocore_private.py
pynamodb/connection/base.py
requirements-dev.txt

botocore 1.28 [changed](https://github.com/boto/botocore/pull/2785) the signature of private method `botocore.client.BaseClient._convert_to_request_dict` adding an `endpoint_url` parameter. We are updating pynamodb to inspect the signature and add this parameter as needed.
P.S. we would probably need to backport this to 5.x.

Workaround for _convert_to_request_dict change

---

docs/release_notes.rst
pynamodb/__init__.py
pynamodb/connection/_botocore_private.py
pynamodb/connection/base.py
tests/test_base_connection.py

In #1083 we've started passing an `endpoint_url` parameter to `_convert_to_request_dict` due to changes made in botocore 1.28. 
All of our integration tests have an explicit `host`, and all our unit tests either mock `_make_api_call` entirely or mock the botocore client, so we didn't realize that `endpoint_url` cannot be `None`. To determine `endpoint_url` in botocore ≥1.28, we must call another private method, `_resolve_endpoint_ruleset`.

Workaround for botocore 1.28 (round 2)

---

pynamodb/connection/base.py
pynamodb/connection/table.py
pynamodb/models.py
tests/data.py
tests/test_base_connection.py
tests/test_model.py
tests/test_table_connection.py
tests/test_transaction.py

When using DynamoDB through a `Model` or `Index` (rather than `(Table)Connection` directly), we will derive the "meta-table" from the model itself rather than make an initial `DescribeTable` call. This has numerous advantages:
- Faster bootstrap (important for lambdas, as pointed out in #422)
- More consistent handling of attribute types: Before this change, if the PynamoDB model definition and the DynamoDB table definition disagreed on a key attribute's type, PynamoDB would use its own idea of the type in some code paths and the underlying type in others. Now it would consistently use its own idea of the type, allowing the erroneous model definition to be spotted sooner.
- Easier testing, since there's no longer a one-off request that only happens once and affects global state.
This …

Do not call DescribeTable for models

---

pynamodb/attributes.py
tests/test_attributes.py

Making it harder to accidentally mutate a default.

Require Attribute default to be immutable or callable

---

tests/test_model.py
tests/test_transaction.py

Remove all meta-table seeding from our tests.
In #1095 we switched to building the meta-table from the model instead of calling `DescribeTable`. This means we no longer need to accommodate an initial `DescribeTable` call in tests.

tests: no more meta-table seeding

---

pynamodb/pagination.py
tests/test_model.py

Improving the first iteration logic in `PageIterator` and `ResultIterator`.
Both iterators had a `_first_iteration` state attribute that could be replaced with better logic:
- In `PageIterator`, it can be replaced with `_is_last_page` which
- is exception-safe (only mutate after we do I/O), and
- (IMO) more directly relates to the state we're handling
- In `ResultsIterator`, we can do without `_first_iteration` (but we should initialize `_index` and `_count`)
Inspired by #1059.

Improve first iteration logic

---

docs/release_notes.rst

Users were naively going to the master branch's release notes, so I suppose we could update them whenever we backport changes (which shouldn't be very often).

Merge release notes from 5.x branch

---

pynamodb/attributes.py
pynamodb/models.py
tests/test_model.py

Making the representation more ergonomic (especially for MapAttributes, which currently have no `__repr__`), by switching to a [attrs](https://www.attrs.org/)-like repr.
Practically, for `Model`s, the repr is changing from
```
my_table_name<HashValue>
my_table_name<HashValue, RangeValue>
```
to
```
MyModel(my_hash_attr="HashValue", spam="ham")
MyModel(my_hash_attr="HashValue", my_range_attr="RangeValue", spam="ham")
```
and for `MapAttribute`s, the repr is changing from
```
<my_module.MyMap object at 0xdeadbeef>
```
to
```
MyMap(spam="ham")
```

AttributeContainer.__repr__: include all attrs

---

pynamodb/exceptions.py
tests/test_exceptions.py

Pull request #786 broke messages for all errors that extend `PynamoDBException`, because it would overwrite the default message with `None`. This change returns the previous behaviour.

Fix exception messages

---

.github/workflows/test.yaml
docs/requirements.txt
pynamodb/_schema.py
pynamodb/attributes.py
pynamodb/constants.py
pynamodb/indexes.py
pynamodb/models.py
setup.py
tests/integration/test_discriminator_index.py
tests/integration/test_transaction_integration.py
tests/test_model.py

With polymorphism, an index's key attribute might be defined only in a derived model (e.g. if it pertains only to a certain kind of model — for other models, it'd be a sparse index), and so it makes sense to add that index only to the derived model, e.g.
```python
class BaseModel(Model):
...
cls = DescriminatorAttribute()
class DerivedIndex(GlobalSecondaryIndex):
class Meta:
index_name = 'derived'
...
ham = UnicodeAttribute(hash_key=True)
class DerivedModel(BaseModel, discriminator='spam'):
ham  = UnicodeAttribute()
index = DerivedIndex()
```
A common pattern in a development environment is to use `Model.create_table`. For a polymorphic model, given you have to pick _one_ model to invoke `create_table` on, it only serves right that you invoke it on the base model.
Before this change, the …

create_table should include polymorphic indexes

---

pynamodb/__init__.py
pynamodb/connection/base.py
tests/integration/base_integration_test.py

In #1095 we stopped calling DescribeTable for models since they can provide their own "meta-table". However, some users are using Connection directly and this was a breaking change for them, so we'll return to calling DescribeTable as needed in those cases.

Connection: call describe_table as needed

---

.gitignore
docs/index.rst
docs/release_notes.rst
docs/upgrading_binary.rst
examples/attributes.py
pynamodb/attributes.py
pynamodb/connection/base.py
pynamodb/models.py
pynamodb/util.py
tests/integration/binary_update_test.py
tests/integration/model_integration_test.py
tests/test_attributes.py
tests/test_base_connection.py
tests/test_binary_legacy_encoding.py
tests/test_model.py

For many versions (verified in versions 3-5) we had a known issue where
1. top-level Binary(Set)Attributes were double-base64-encoded in the underlying DynamoDB table item
2. nested Binary(Set)Attributes were unusable: every serialization would add another round of Base64 encoding(!), so nested binary attributes could not have been used in practice
Clearly (1) is inefficient and (2) is unusable, and we wanted PynamoDB to be efficient (and not broken) by default, but similarly didn't want to risk breaking systems during an upgrade to PynamoDB 6. With that in mind, we're introducing a `legacy_encoding` required parameter to `BinaryAttribute` and `BinarySetAttribute`, the rationale being a new required parameter will prompt an informed decision. The parameter will exist throughout the …

Fix double base64 of binary attributes

---

docs/release_notes.rst
pynamodb/__init__.py
pynamodb/connection/_botocore_private.py
pynamodb/connection/base.py
tests/test_base_connection.py

botocore 1.28 [changed](https://github.com/boto/botocore/pull/2785) the signature of private method `botocore.client.BaseClient._convert_to_request_dict` adding an `endpoint_url` parameter. We are updating pynamodb to inspect the signature and add this parameter as needed.
Backport to 4.x of #1083 and #1087.

4.x: workaround for _convert_to_request_dict change (#1083)

---

docs/optimistic_locking.rst
examples/attributes.py
examples/optimistic_locking.py

Since #1100, we don't need to override `__repr__` anymore to get a useful repr.

Remove __repr__s from docs and examples

---

.readthedocs.yaml
docs/api.rst
docs/conf.py
docs/requirements.txt
pynamodb/exceptions.py

RTD (ReadTheDocs) improvements:
- Add `.readthedocs.yaml` as it's apparently the [preferred way to configure RTD](https://docs.readthedocs.io/en/stable/config-file/v2.html)
- Update the RTD theme version
- Update the Sphinx version ≥ 2 (RTD defaults to version 1, which doesn't support the `autodoc_default_options.members = True` setting).
Documentation improvements:
- Include class members in generated API documentation by default. Previously some classes' docs (especially exceptions) were generated without members.
- Document some of the members of exception classes.

Update docs framework & exception docs

---

docs/api.rst
docs/transaction.rst
pynamodb/connection/base.py
pynamodb/exceptions.py
tests/integration/test_transaction_integration.py

This will allow the caller to know e.g. which of the transaction items ran into a conflict, which can sometimes allow app logic to better handle the error without needing to make more requests.
A transaction cancellation response has the following shape:
```json
{
"__type": "com.amazonaws.dynamodb.v20120810#TransactionCanceledException",
"CancellationReasons": [
{
"Code": "None"
},
{
"Code": "ConditionalCheckFailed",
"Message": "The conditional request failed"
}
],
"Message": "Transaction cancelled, please refer cancellation reasons for specific reasons [None, ConditionalCheckFailed]"
}
```
where the first item was not a reason for cancellation and the second one was.
Curiously, this field is not parsed by botocore: only some of the AWS SDKs (Java, Ruby...) parse it.

Expose transaction cancellation reasons

---

tests/integration/test_discriminator_index.py

Uses `pytest.mark.ddblocal` on integration tests that use DynamoDB local.  As I forked the repo to try my first contribution to the project, unit tests immediately failed on these tests cases.

Mark ddblocal on integration tests that need it.

---

pynamodb/connection/base.py
pynamodb/connection/table.py
tests/test_table_connection.py

An UnrecognizedClientException exception is thrown when using threads to reference a table.
1. Save the following code as repro.py and modify VALID_ACCESS_KEY and VALID_SECRET_ACCESS_KEY with valid `AWS_ACCESS_KEY_ID` and  `AWS_SECRET_ACCESS_KEY`.
```python
import time, sys, os, traceback, io
from concurrent.futures import ThreadPoolExecutor
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute
os.environ['AWS_ACCESS_KEY_ID'] = "INVALID_KEY"
os.environ['AWS_SECRET_ACCESS_KEY'] = "INVALID_SECRET"
class UserModel(Model):
class Meta:
table_name = 'test_accout_dynamodb222'
region = 'us-west-1'
aws_access_key_id = 'VALID_ACCESS_KEY' 
aws_secret_access_key = 'VALID_SECRET_ACCESS_KEY'
email = UnicodeAttribute(hash_key=True)
first_name = UnicodeAttribute()
last_name = …
```

AWS account credentials in the Model Meta class is not used in threaded code

---

.github/workflows/release.yaml

Looking at #1158, I've realized that contributors don't have access to the Test PyPi secret. :(
In #1123 I've made it so that pull requests exercise building, which is still a good idea, but uploading to Test PyPi is futile since it mostly fails due to the version already existing, and it also fails for contributors.
So I'd like to move it to a [manual workflow](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow).

Upload to Test PyPi only on manual trigger

---

docs/optimistic_locking.rst
docs/release_notes.rst
pynamodb/__init__.py
pynamodb/attributes.py
pynamodb/models.py
pynamodb/transactions.py
tests/integration/test_transaction_integration.py
tests/test_model.py

Add a flag for controlling whether `Model.save`, `Model.update` and `Model.delete` add a condition that the persisted version is the same as the in-memory one, defaulting to `True` (the "safe" behavior)
This is a backport to 5.x.

Add 'add_version_condition' arg

---

pynamodb/attributes.py
pynamodb/expressions/operand.py
tests/integration/model_integration_test.py
tests/test_expressions.py

Fixes #962.
Empty sets are not supported by DynamoDB. Currently we're representing empty sets by unsetting the attribute (hence it's indistinguishable from unsetting), i.e.
```python
m1.my_set = set()
m1.save()
m2.my_set = None
m2.save()
```
then
```python
m1.refresh()
m2.refresh()
assert m1.my_set == m2.my_set == None
```
Another way to empty the set should be through an update expression:
```python
m1.update([MyModel.my_set.set([]))
```
We're not changing this semantic here, but we're making it so that `m1.update([MyModel.my_set.set([]))` doesn't crash in botocore.
When preparing an update expression, we've been sending update expressions like `{':0': {'NS': None}}` which crashed botocore with "TypeError: 'NoneType' object is not iterable". The PR addresses it by using a `REMOVE` action …

Fix updating set to empty

---

.readthedocs.yaml
docs/release_notes.rst
docs/requirements.txt
pynamodb/__init__.py
pynamodb/connection/base.py

Updates for https://github.com/boto/botocore/commit/826b78c54dd87b9da368e9ab6017d8c4823b28c1.
Fixes #1205.

Fix compatibility with botocore 1.33.2

---

setup.cfg

Use `license_files` instead.
https://setuptools.pypa.io/en/latest/userguide/declarative_config.html
Fixes warnings like:
```
!!
********************************************************************************
The license_file parameter is deprecated, use license_files instead.
This deprecation is overdue, please update your project and remove deprecated
calls to avoid build errors in the future.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
!!
```

In setup.cfg, avoid deprecated license_file

---

docs/release_notes.rst

release_notes: document more breaking changes

---

docs/transaction.rst
pynamodb/connection/base.py
pynamodb/exceptions.py
tests/integration/test_transaction_integration.py

When sending "ReturnValuesOnConditionCheckFailure": "ALL_OLD" the item is returned within the CancellationReasons list.
https://github.com/pynamodb/PynamoDB/issues/1225

return Item in cancellation_reasons when transaction fails and return_values=ALL_OLD

---

pynamodb/connection/base.py
requirements-dev.txt
tests/test_base_connection.py

Per documentation, adding `extra_headers` is intended for proxies that strip them, so they should be added after signature.
Fixes #1241.

Add extra_headers after signature

---

docs/updates.rst

This pull request will change unintended indentation on Read The Docs documentation
**As-Is : "set action" has the different indentation from others** 
**To-Be :**

fix indentation of sidebar on documentation 

---

docs/quickstart.rst

This removes the reference to the default region being us-east-1 if not specified in the Model's Meta class. This is not longer true as of version 6.0.0.

chore(docs): remove default region reference in docs

---

docs/release_notes.rst
pynamodb/models.py
tests/test_model.py

This adds a `wait` argument that will make the `delete_table` call block until the DynamoDB table is fully deleted if set to `True`. It defaults to `False` to not break the existing behavior.

feat: add wait argument to `Model.delete_table`
